name: nexus-userbot
services:
  - name: nexus-userbot
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 8080
        protocol: http
    env:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8080"
    regions:
      - fra
    instance_types:
      - nano
    autoscaling:
      min: 1
      max: 1
    health_checks:
      - path: /
        port: 8080
        initial_delay_seconds: 60
        timeout_seconds: 10
        period_seconds: 30