services:
  - type: web
    name: nexus-userbot
    env: python
    plan: free
    buildCommand: pip install -r dependencies.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: COMMAND_PREFIX
        value: "."
      - key: BOT_VERSION
        value: "2.0"